### PR TITLE
Disposing graphic resources from icon building

### PR DESCRIPTION
**Pull request by Logerfo**
With 15 seconds interval, the application could would crash after approximately 12 hours. I did this today, so I'm not sure if it really fixes, but disposing resources is a good pratice anyway.
See: https://stackoverflow.com/questions/12026664/a-generic-error-occurred-in-gdi-when-calling-bitmap-gethicon

### CODE REVIEW

**Comment by Logerfo** [comment]
Disposing didn't help, but I'm keeping them anyway. Testing https://github.com/davidvidmar/Crycker/pull/14/commits/2df974105f18c34fa0338f0eda784f8c709dfe47 now, according to [this](https://msdn.microsoft.com/en-us/library/system.drawing.icon.fromhandle%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

**Comment by davidvidmar** [comment]
I have never experienced a problem with crashing, I'm running it 24/7 on two machines. Any news on your last test?

**Comment by Logerfo** [comment]
I'm running my own version (with these changes) for over a year now and facing no issue.

**Comment by davidvidmar** [comment]
Great. I'll run some more test on my side and merge when confirmed it works
for me too. Thanks for contributing.

**Pull request merged**
