### PR TITLE
Percentage notification

### PR DESCRIPTION
**Pull request by Logerfo**
#4
Some commits acting as a build up, followed by the real thing.
Do not merge yet! `ShowBalloonTip` method is not working and I have no idea why ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by Logerfo** [comment]
@davidvidmar does this work for you? I even tried a simple `ShowBalloonTip` at the icon click event and the balloon won't ever show. No idea what's wrong...

**Comment by davidvidmar** [comment]
I'm testing it and it does work, yes. Also tried simple click on tray icon (I did change from subscribing to Click event to subscribing to MouseClick so I can filter left click only) and notification pops up. I think I'll merge this code and later look if we can switch to Windows 8/10 toast notifications.

image

**Comment by Logerfo** [comment]
Well, then I guess my windows notification is broken somehow. Since I can't test it, that's how far I'll get. You can merge it if you think it's good to go, and you have write access to this branch if you don't.

**Comment by davidvidmar** [comment]
Hi, I'll merge your PR as soon as I find some time, possibly this weekend. Thanks for contributing!

**Comment by davidvidmar** [comment]
I really like this, it does come handy. I think there is one more thing worth doing before releasing a new version - converting seconds to minutes when the interval is more than 60 seconds. This way we don't get the text .... in last 3000 secnods, but 5 minutes.

**Comment by Logerfo** [comment]
Check out https://github.com/Humanizr/Humanizer

**Comment by davidvidmar** [comment]
Humanizer is very cool, but so far I have managed to avoid any dependencies to keep the solution small and simple. I want to keep it that way.

**Pull request merged**
